### ISSUE TITLE
It's showing NullPointerException when invoking interface ITrueCallback method

### ISSUE THREAD

**Issue by subrud** [truecaller/android-full-stack-sdk#1]
The error I'm getting :

```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.truecaller.android.sdk.ITrueCallback.onSuccessProfileShared(com.truecaller.android.sdk.TrueProfile)' on a null object reference
        at com.truecaller.android.sdk.clients.c.a(Unknown Source:62)
        at com.truecaller.android.sdk.TrueSDK.onActivityResultObtained(Unknown Source:21)
        at com.ownline.tests.TestTrueCaller.onActivityResult(TestTrueCaller.java:89)
```

Here's onActivityResult() : 

```
protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        Log.d(TAG, "onActivityResult: called");
        trueSDK.onActivityResultObtained( this, resultCode, data);
    }
```
Here's onCreate() :
```
 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test_true_caller);

        TrueSdkScope trueScope = new TrueSdkScope.Builder(this, iTrueCallback)
                .consentMode(TrueSdkScope.CONSENT_MODE_POPUP)
                .consentTitleOption(TrueSdkScope.SDK_CONSENT_TITLE_VERIFY)
                .footerType(TrueSdkScope.FOOTER_TYPE_SKIP)
                .build();
        TrueSDK.init(trueScope);
        trueSDK = TrueSDK.getInstance();
        Log.d(TAG, "onCreate: isTrueSdk = " + TrueSDK.getInstance().isUsable());

        trueButton = findViewById(R.id.true_btn);
        tButton = findViewById(R.id.true_button);
        trueButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                verifyWithTrueCaller ();
            }
        });

    }
```
verifyWithTrueCaller() method :

```
private void verifyWithTrueCaller() {

        if (trueSDK.isUsable()) {
            Log.d(TAG, "verifyWithTrueCaller:" +
                    " usable");

        }

        trueSDK.getUserProfile(this);

        iTrueCallback = new ITrueCallback() {
            @Override
            public void onSuccessProfileShared(@NonNull TrueProfile trueProfile) {
                Log.d(TAG, "onSuccessProfileShared: " + trueProfile.phoneNumber);
                Log.d(TAG, "onSuccessProfileShared: " + trueProfile.email);
                Log.d(TAG, "onSuccessProfileShared: " + trueProfile.firstName);
                Log.d(TAG, "onSuccessProfileShared: " + trueProfile.lastName);
            }

            @Override
            public void onFailureProfileShared(@NonNull TrueError trueError) {
                Log.d(TAG, "onFailureProfileShared: " + trueError.getErrorType());
            }

            @Override
            public void onVerificationRequired() {

            }
        };

    }
```

**Comment by praveenverma720** [comment]
You need to initialize ITrueCallback before initialization of   TrueSdkScope check the Below Example. 

**Declare the variables at global level  **

`private TrueSdkScope trueScope;
    private TrueSDK trueSDK;
    private TrueButton button_trueCaller;

    private final ITrueCallback sdkCallback = new ITrueCallback() {

        @Override
        public void onSuccessProfileShared(@NonNull final TrueProfile trueProfile) {

            // This method is invoked when either the truecaller app is installed on the device and the user gives his
            // consent to share his truecaller profile OR when the user has already been verified before on the same
            // device using the same number and hence does not need OTP to verify himself again.

            Log.d( TAG, "Verified without OTP! (Truecaller User): " + trueProfile.firstName );
        }

        @Override
        public void onFailureProfileShared(@NonNull final TrueError trueError) {
            // This method is invoked when some error occurs or if an invalid request for verification is made

            Log.d( TAG, "onFailureProfileShared: " + trueError.getErrorType() );
        }

        @Override
        public void onVerificationRequired() {

            // This method is invoked when truecaller app is not present on the device or if the user wants to
            // continue with a different number and hence, missed call verification is required to complete the flow
            // You can initiate the missed call verification flow from within this callback method by using :

           // TrueSDK.getInstance().requestVerification("IN", PHONE_NUMBER_STRING, apiCallback);

            //  Here, the first parameter is the country code of the mobile number for which the verification needs to be
            // triggered and PHONE_NUMBER_STRING should be the 10-digit mobile number of the user

        }
    };`

**Now initialize trueSdkScope inside the onCreate Method like this **

`trueScope = new TrueSdkScope.Builder(this, sdkCallback)
                .consentMode(TrueSdkScope.CONSENT_MODE_POPUP)
                .consentTitleOption(TrueSdkScope.SDK_CONSENT_TITLE_VERIFY)
                .footerType(TrueSdkScope.FOOTER_TYPE_CONTINUE)
                .build();

        TrueSDK.init(trueScope);
        trueSDK = TrueSDK.getInstance();

        button_trueCaller = (TrueButton) findViewById(R.id.button_true);`

**onActivityResult() **
`public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        trueSDK.onActivityResultObtained( this, resultCode, data);
    }`

**Now set the onClcikListner on trueButton**

`button_trueCaller.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (TrueSDK.getInstance().isUsable()) {

                    // get user profile from trucaller app
                    trueSDK.getUserProfile(LoginActivity.this);


                } else {
Log.d(TAG, "Handle Other Condition ");
                }
            }
        });`

I hope it will work for you. If you need any help regarding this follow me on github.
